# This entire config is deprecated for now.
name: Publish

on:
  release:
    # Run this workflow when a new GitHub release is created.
    types: [released]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Builds the release artifacts of the library.
      - name: Release build
        working-directory: ./library
        run: ./gradlew jar

        # Generates other artifacts.
      - name: Source jar and dokka
        working-directory: ./library
        run: ./gradlew sourcesJar javadocJar

        # Runs upload, and then closes & releases the repository.
      - name: Publish to MavenCentral
        working-directory: ./library
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}